baseURL = 'https://vthsa.in/'
theme = 'hugo-bearblog'
languageCode = 'en-us'
title = '🔠'

enableRobotsTXT = true

[permalinks]
blogs = "/:slug/"
writings = "/writings/:slug"
tags = "/blog/:slug"

[params]
	description = "Vathsa's personal website"
	hideMadeWithLine = true